.\" Copyright (c) 2023, Matthew R. Muller, Matthew P. Dargan.
.\" SPDX-License-Identifier: BSD-3-Clause
.TH bfp_server 1 "November 9, 2023" "bfp_server" "bfp_server Manual"
.SH NAME
bfp_server \- Basic File Protocol Server
.SH SYNOPSIS
.B bfp_server
.SH DESCRIPTION
.B bfp_server
serves Basic File Protocol (BFP) content to clients.

BFP is a file-sharing protocol that enables users to host and access files on
POSIX-compliant systems. It operates over TCP/IP, using port 8039 as the
designated port.

When a client connects to a BFP server with a valid IP address and port, the
server responds according to the client's request:

.IP "1. Invalid Request:"
When an invalid directory or file path is requested, the server responds with
the null character (NUL) to indicate the request's invalidity.

.IP "2. Directory Listing:"
When a valid directory is requested, the server responds with the directory
information, including subdirectories and filenames, allowing clients to
navigate and explore the available files within the specified directory.

.IP "3. File Transfer:"
When a valid file path is requested, the server responds with the data of the
requested file.
